databases:
  - name: empresaDjangoDB
    plan: free
    databaseName: empresaDjangoDB
    user: adminDjango

services:
  - type: web
    plan: free
    name: empresaDjango
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn empresaDjango.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: empresaDjangoDB
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4