databases:
  - name: empresaDjangoDB
    plan: free
    databaseName: empresadjangodb
    user: empresadjangodb_user

services:
  - type: web
    plan: free
    name: empresaDjango
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn empresaDjango.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: empresadjangodb
          property: postgresql://empresadjangodb_user:yHdjn8yOwCwHvfG07NNslt8ptjigR5GC@dpg-cslsp7l6l47c73aaeca0-a/empresadjangodb
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4